
## Install HAProxy
  - name: Install HAProxy
    apt:
      pkg:
      - haproxy
    become: true

## Configure HAProxy
  - name: Configure HAProxy
    template:
      src: ../templates/loadbalancer/haproxy.cfg.j2
      dest: "/etc/haproxy/haproxy.cfg"
    become: true

  - name: Restart HAProxy service
    systemd:
      state: reloaded
      enabled: yes
      name: haproxy
    become: yes