---

## Disable password prompt on sudo
  - name: Allow 'sudo' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
    become: true

## Install dependencies
  - name: Install nessesary applications
    apt:
      pkg:
      - socat
      - conntrack
      - ipset
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - software-properties-common
    become: true

#  - include: playbooks/install_crictl.yaml  

## Disable swap

  - name: Disable swap
    command: swapoff -a
    become: true

  - name: Remove swapfile from /etc/fstab
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'
    become: true


## Setup iptables to legacy
  - name: set iptables to legacy
    command: update-alternatives --set iptables /usr/sbin/iptables-legacy
    become: true


## Setup kernel modules
  - name: Set-up kernel modules
    copy:
      content: |
                overlay
                br_netfilter
      dest: /etc/modules-load.d/containerd.conf
    become: true

  - name: Add overlay module
    modprobe:
      name: overlay
      state: present
    become: true

  - name: Add br_netfilter module
    modprobe:
      name: br_netfilter
      state: present
    become: true
  
  - name: Reload sysctl
    command: sysctl --system
    become: true
