---
  
  - name: Download weave tool
    get_url:
      url: https://git.io/weave
      dest: /tmp/weave

  - name: Copy weave to /usr/local/bin/
    copy:
      remote_src: yes
      mode: +x
      owner: root
      group: root
      src: /tmp/weave
      dest: /usr/local/bin/weave
    become: true

  